title: Budget Options
description: >-
  Community-built proposals for bridging the school budget gap through
  transparency, volunteer coordination, and shared service grants.
url: "https://schools.siliconsaga.net"
baseurl: ""

remote_theme: just-the-docs/just-the-docs@v0.10.1

color_scheme: dark

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# GitHub link in header
gh_edit_link: true
gh_edit_link_text: "View this page on GitHub"
gh_edit_repository: "https://github.com/SiliconSaga/schools"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"

# Footer
footer_content: >-
  <a href="https://github.com/SiliconSaga/schools/issues">Suggest improvements to this site</a>
  &nbsp;|&nbsp;
  <a href="https://docs.google.com/forms/d/e/1FAIpQLSfPpBHw2F13tZXD54vfKXXNQywjaz93KaJXdMLWG0AnE51csw/viewform">Give feedback to the West Orange School District</a>

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
